### ISSUE TITLE
Missing extension android-maven-plugin:3.5.2

### ISSUE THREAD

**Issue by Hirschen** [stephanenicolas/Quality-Tools-for-Android#2] opened 2013-03-14 16:00 UTC
When doing mvn clean install:

Unresolveable build extension: Plugin com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.2-SNAPSHOT or one of its dependencies could not be resolved: Failure to find com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.5.2-SNAPSHOT in http://oss.sonatype.org/content/repositories/jayway-snapshots/

Seems like the snapshot is missing at the specific address. Anything Im doing wrong maybe?

**Comment by stephanenicolas** [comment] 2013-03-14 19:25
This issue is a duplicate of issue #1.

**Closed as completed by stephanenicolas** 2013-03-14 19:25 UTC
Labels: duplicate
